enum ErrorType {
  NOT_FOUND_ERROR = "NOT_FOUND",
  UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR",
  FORBIDDEN_ERROR = "FORBIDDEN_ERROR",
  BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNPROCESSABLE_ENTITY_ERROR = "UNPROCESSABLE_ENTITY_ERROR",
  CONFLICT_ERROR = "CONFLICT_ERROR",
  TOO_MANY_REQUESTS_ERROR = "TOO_MANY_REQUESTS_ERROR",
  MISSING_TOKEN_ERROR = "MISSING_TOKEN_ERROR",
  INVALID_TOKEN_ERROR = "INVALID_TOKEN_ERROR",
  MISSING_API_KEY_ERROR = "MISSING_API_KEY_ERROR",
  INVALID_API_KEY_ERROR = "INVALID_API_KEY_ERROR",
  APP_LIMIT_EXCEED_ERROR = "APP_LIMIT_EXCEED_ERROR",
  APP_USER_LIMIT_EXCEED_ERROR = "APP_USER_LIMIT_EXCEED_ERROR",
  INSUFFICIENT_BALANCE_ERROR = "INSUFFICIENT_BALANCE_ERROR",
}

export default ErrorType;
